### ISSUE TITLE
Add support for arbitrary mods directory

### ISSUE THREAD

**Issue by ac2pic** [dmitmel/ccloader3#1]
Let `assets/mods/` be the default directory, but allow a user to specify an alternative directory.

**Comment by dmitmel** [comment]
Where should the configuration be stored? Right now this is trivial to put in `user-config.js` because the user configuration is loaded before the mod metadata.

**Comment by ac2pic** [comment]
A central configuration place would be most ideal. `user-config.js` should be sufficient.
