### ISSUE TITLE
Ability to hijack a request and return a custom response

### ISSUE THREAD

**Issue by ac2pic** [dmitmel/ccloader3#4]

**Comment by dmitmel** [comment]
While this should be easily doable when I add general-purpose resource pipeline hooks (`beforeSend`, `prePatch`, `postPatch`, `finalFixes`), I'm not entirely convinced this is useful in practice. What are the usecases?

**Comment by ac2pic** [comment]
Defining my own custom file format handler.

**Comment by dmitmel** [comment]
What do you mean?

**Comment by ac2pic** [comment]
Scratch that. If something makes a request, and that file may does not exist on the filesystem, I would like to return a custom response that is not an error.

**Comment by dmitmel** [comment]
To be fair that's just the reworded version of the title, I understand what this system has to do Not a use-case though. Anyway, my current opinion on this feature is: it can be implemented, theoretically with a separate mod provided that programmable resource pipeline exists (I'd like to have this for Localize Me, but so far Localize Me works fine without it), but as there is no concrete use-case (yet?) this is not blocking the 3.0.0 release.

**Comment by ac2pic** [comment]
I intend on using this to implement djson fake file feature. It will dynamically generate a file that may or may not change each time the file is loaded. The most immediate use case is dynamically generated map files.
